services:
  react:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
  html-client:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3002:80"
    networks: app-network

  rails:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3001:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
