name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.1

      - name: Install dependencies
        run: |
          cd server/product_app
          gem install bundler
          bundle install

      - name: Set up Database
        run: |
          cd server/product_app
          cp config/database.yml.github-actions config/database.yml
          bin/rails db:create RAILS_ENV=test
          bin/rails db:migrate RAILS_ENV=test

      - name: Run RSpec tests
        run: |
          cd server/product_app
          bundle exec rspec

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build HTML Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/html-app:latest ./client/html-client

      - name: Push HTML image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/html-app:latest

      - name: Build Rails Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/rails-app:latest ./server/product_app

      - name: Push Rails image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/rails-app:latest

      - name: Build React Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/react-app:latest ./client/react-client

      - name: Push React image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/react-app:latest

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/html-app:latest
            docker stop html-app || true
            docker rm html-app || true
            docker run -d -p 3002:80 --name html-app ${{ secrets.DOCKERHUB_USERNAME }}/html-app:latest

            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/rails-app:latest
            docker stop rails-app || true
            docker rm rails-app || true
            docker run -d -p 3001:3000 --name rails-app ${{ secrets.DOCKERHUB_USERNAME }}/rails-app:latest

            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/react-app:latest
            docker stop react-app || true
            docker rm react-app || true
            docker run -d -p 3000:3000 --name react-app ${{ secrets.DOCKERHUB_USERNAME }}/react-app:latest
