name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest .

      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
            docker stop my-app || true
            docker rm my-app || true

            docker stop my-app-react || true
            docker rm my-app-react || true
            docker run -d -p 3000:3000 --name my-app-react ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest

            docker stop my-app-html || true
            docker rm my-app-html || true
            docker run -d -p 3002:80 --name my-app-html ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest

            docker stop my-app-rails || true
            docker rm my-app-rails || true
            docker run -d -p 3001:3000 --name my-app-rails ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
